In [3]:
# pandas

import pandas as pd

In [4]:
df = pd.read_csv("Retail_Dataset_Modified.csv")

In [25]:
df

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

In [26]:
df.tail()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

In [27]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
print(list1+list2)

#list just joined (Concatenated), no Addition..

[1, 2, 3, 4, 5, 6]

In [28]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1+arr2)

#acutal element-wise addition..

[5 7 9]

In [29]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1/arr2)

[0.25 0.4  0.5 ]

In [30]:
print(df.head())

         Store_ID                      Store_Name    Brand_Name    Store_Type  \
0     BX_PUNE_034    BrandX_India Superstore Pune  BrandX_India      Flagship
1   BX_MUMBAI_023  BrandX_India Superstore Mumbai  BrandX_India  Street Store
2     BX_PUNE_073        BrandX_India Trends Pune  BrandX_India      Flagship
3  BX_CHENNAI_061     BrandX_India Trends Chennai  BrandX_India    Mall Store
4  BX_CHENNAI_033    BrandX_India Connect Chennai  BrandX_India    Mall Store

      City City_Tier     Product_Name   Category     Sub_Category  \
0     Pune     Tier1   Green Tea 100g  Groceries              Tea
1   Mumbai     Metro  White Sugar 1kg  Groceries            Sugar
2     Pune     Tier1   Levi's T-Shirt    Clothes         T-Shirts
3  Chennai     Metro    Adidas Hoodie    Clothes          Jackets
4  Chennai     Metro    PlayStation 5    Gadgets  Gaming Consoles

  Product_Stage  ... Brand_Loyalty Brand_Awareness  Price_Competitiveness  \
0     Declining  ...          70.8            75.7               Standard
1     Declining  ...          80.5            81.5            Competitive
2     Declining  ...          68.5            76.7               Standard
3    New Launch  ...          92.4            88.0            Competitive
4     Declining  ...          82.9            89.5            Competitive

   Weather_Impact Delivery_Time  Shipping_Cost  Month  Year  Quarter  Season
0             Low           6.0             57      1  2022       Q1  Spring
1             Low           4.0             99      1  2022       Q1  Spring
2          Medium           4.0            101      1  2022       Q1  Spring
3          Medium           5.0             79      1  2022       Q1  Spring
4             Low           2.0            110      1  2022       Q1  Spring

[5 rows x 47 columns]

Task 2: Explore DataFrame Structure

In [31]:
#Display Dataset Shape


print("Dataset Shape:")
print(df.shape)

Dataset Shape:
(5171, 47)

In [32]:
#Display Column Names

print("Columns:")
print(df.columns)

Columns:
Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='str')

In [33]:
#Display Dataset Information

print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5171 non-null   str
 1   Store_Name             5171 non-null   str
 2   Brand_Name             5171 non-null   str
 3   Store_Type             5171 non-null   str
 4   City                   5109 non-null   str
 5   City_Tier              5171 non-null   str
 6   Product_Name           5098 non-null   str
 7   Category               5171 non-null   str
 8   Sub_Category           5171 non-null   str
 9   Product_Stage          5171 non-null   str
 10  Quantity_Available     5171 non-null   str
 11  Units_Sold             5171 non-null   str
 12  Unit_Price             5171 non-null   int64
 13  Cost_Price             5171 non-null   int64
 14  Revenue                5099 non-null   str
 15  Profit_Margin          5171 non-null   float64
 16  Average_Order_Value    5171 non-null   int64
 17  Inventory_Turnover     5171 non-null   float64
 18  Days_of_Stock          5171 non-null   int64
 19  Customer_Segment       5171 non-null   str
 20  Sales_Channel          5171 non-null   str
 21  Payment_Method         5171 non-null   str
 22  Supplier               5103 non-null   str
 23  Supplier_Rating        5171 non-null   str
 24  Promotion_Type         5171 non-null   str
 25  Promotion_Impact       5171 non-null   float64
 26  Max_Discount_Offered   5171 non-null   int64
 27  Return_Rate            5171 non-null   float64
 28  Return_Reason          5171 non-null   str
 29  Customer_Satisfaction  5094 non-null   float64
 30  Online_Rating          5171 non-null   float64
 31  Review_Count           5171 non-null   int64
 32  Sales_Rep_Experience   5171 non-null   int64
 33  Sales_Rep_Rating       5171 non-null   float64
 34  Market_Share           5171 non-null   float64
 35  Competition_Level      5171 non-null   str
 36  Competitor_Count       5171 non-null   int64
 37  Brand_Loyalty          5171 non-null   float64
 38  Brand_Awareness        5171 non-null   float64
 39  Price_Competitiveness  5171 non-null   str
 40  Weather_Impact         5171 non-null   str
 41  Delivery_Time          5111 non-null   float64
 42  Shipping_Cost          5171 non-null   str
 43  Month                  5171 non-null   int64
 44  Year                   5171 non-null   int64
 45  Quarter                5171 non-null   str
 46  Season                 5171 non-null   str
dtypes: float64(11), int64(10), str(26)
memory usage: 1.9 MB
None

Task 3: Identify Key Columns

In [34]:
#Display Key Columns

print(df.columns)

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='str')

In [35]:
Category_Array = np.array(df["Category"])
print(Category_Array)

['Groceries' 'Groceries' 'Clothes' ... 'Electronics' 'Clothes'
 'Electronics']

In [37]:
Store_Name_Array = np.array(df["Store_Name"])
print(Store_Name_Array)

['BrandX_India Superstore Pune' 'BrandX_India Superstore Mumbai'
 'BrandX_India Trends Pune' ... 'BrandX_India Gadget Zone Kanpur'
 'BrandX_India Style Mumbai' 'BrandX_India Electronics Delhi']

In [38]:
Brand_Name_Array = np.array(df["Brand_Name"])
print(Brand_Name_Array)

['BrandX_India' 'BrandX_India' 'BrandX_India' ... 'BrandX_India'
 'BrandX_India' 'BrandX_India']

In [39]:
Store_Type_Array = np.array(df["Store_Type"])
print(Store_Type_Array)

['Flagship' 'Street Store' 'Flagship' ... 'Flagship' 'Street Store'
 'Flagship']

In [40]:
City_Array = np.array(df["City"])
print(City_Array)

['Pune' 'Mumbai' 'Pune' ... 'Kanpur ' 'Mumbai ' 'Delhi ']

In [41]:
Product_Name_Array = np.array(df["Product_Name"])
print(Product_Name_Array)

['Green Tea 100g' 'White Sugar 1kg' "Levi's T-Shirt" ... 'Dell XPS 13'
 'Nike Air Max' 'MacBook Air M2']

In [42]:
revenue_array = np.array(df["Revenue"])
print(revenue_array)

['7320' '1645' '66340' ... '982202' '244244' '1408680']

In [43]:
#Access the First Revenue Value Using Indexing

print("First Revenue Value:")
print(revenue_array[0])

First Revenue Value:
7320

In [44]:
#Access the Last Revenue Value

print("Last Revenue Value:")
print(revenue_array[-1])

Last Revenue Value:
1408680

In [45]:
#Slice the First Five Revenue Records

print("First Five Revenue Values:")
print(revenue_array[0:5])

First Five Revenue Values:
['7320' '1645' '66340' '77748' '1976364']

In [46]:
#Slice Revenue Values from Index 10 to 20

print("Revenue Values from Index 10 to 20:")
print(revenue_array[10:21])

Revenue Values from Index 10 to 20:
['318948' '25636' '3893616' '375382' '118697' '544334' '144100' '5363'
 '4894784' '116721' '2264131']

In [47]:
#Create a Two-Dimensional Array

sales_array = np.array(df[["Units_Sold", "Profit_Margin"]])

print(sales_array)

[['24' 21.64]
 ['35' 29.79]
 ['31' 19.86]
 ...
 ['13' 29.86]
 ['22' 16.53]
 ['12' 29.34]]

In [48]:
#Access the First Row of the Array

print("First Row:")
print(sales_array[0])

First Row:
['24' 21.64]

In [49]:
#Access the Profit Margin Column

print("Profit Margin Column:")
print(sales_array[:,1])

Profit Margin Column:
[21.64 29.79 19.86 ... 29.86 16.53 29.34]

Task 2: Perform Operations

In [50]:
#Display the First 10 Revenue Values

first_ten = revenue_array[0:10]
print(first_ten)

['7320' '1645' '66340' '77748' '1976364' '18511' '3026641' '4860270'
 '870570' '35552']

In [51]:
#Find Total Revenue of First 10 Records

print("Total Revenue:")
print(np.sum(first_ten))

Total Revenue:
7320164566340777481976364185113026641486027087057035552

In [52]:
#Find Highest Revenue from First 10 Records

print("Maximum Revenue:")
print(np.max(first_ten))

Maximum Revenue:
870570

In [53]:
#Find Lowest Revenue from First 10 Records

print("Lowest Revenue:")
print(np.min(first_ten))

Lowest Revenue:
1645