In [5]:
import numpy as np
import pandas as pd

In [6]:
retail = pd.read_csv("Retail_Dataset_Cleaned.csv")

In [7]:
df.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,Bx_Pune_034,Brandx_India Superstore Pune,Brandx_India,Flagship,Pune,Tier1,Green Tea 100G,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57.0,1,2022,Q1,Spring
1,Bx_Mumbai_023,Brandx_India Superstore Mumbai,Brandx_India,Street Store,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99.0,1,2022,Q1,Spring
2,Bx_Pune_073,Brandx_India Trends Pune,Brandx_India,Flagship,Pune,Tier1,Levi'S T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101.0,1,2022,Q1,Spring
3,Bx_Chennai_061,Brandx_India Trends Chennai,Brandx_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79.0,1,2022,Q1,Spring
4,Bx_Chennai_033,Brandx_India Connect Chennai,Brandx_India,Mall Store,Chennai,Metro,Playstation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110.0,1,2022,Q1,Spring

In [ ]:

retail.groupby('City')['Revenue'].sum().head()

City
Ahmedabad    2.655276e+08
Bangalore    8.407997e+08
Bhopal       1.079895e+08
Chennai      7.419116e+08
Delhi        1.661122e+09
Name: Revenue, dtype: float64

In [9]:
category_revenue = pd.pivot_table(
    df,
    values="Revenue",
    index="Category",
    aggfunc="sum"
)

category_revenue

                      Revenue
Category
Clothes          2.220630e+08
Electronics      3.623063e+09
Gadgets          2.654379e+09
Groceries        2.394028e+07
Home Appliances  5.584119e+08

In [15]:
City_revenue = pd.pivot_table(
    df,
    values="Revenue",
    index="City",
    aggfunc="sum"
)

City_revenue

                    Revenue
City
Ahmedabad      2.655276e+08
Bangalore      8.407997e+08
Bhopal         1.079895e+08
Chennai        7.419116e+08
Delhi          1.661122e+09
Hyderabad      6.597958e+08
Jaipur         2.670945e+08
Kanpur         8.430218e+07
Lucknow        9.486221e+07
Mumbai         1.674840e+09
Nagpur         7.479879e+07
Pune           2.936829e+08
Surat          2.340634e+08
Visakhapatnam  8.106636e+07

In [16]:
segment_revenue = pd.pivot_table(
    df,
    values="Revenue",
    index="Customer_Segment",
    aggfunc="sum"
)

segment_revenue

                       Revenue
Customer_Segment
Budget            1.712615e+09
Luxury            1.863606e+09
Mid-Range         1.822548e+09
Premium           1.683088e+09

Task 2: Aggregating Retail Data for Business Decision-Making

In [19]:
#Calculate Multiple Revenue Statistics Category-wise

category_summary = pd.pivot_table(
    df,
    values="Revenue",
    index="Category",
    aggfunc=["sum", "mean", "max", "min"]
)

category_summary

                          sum          mean         max       min
                      Revenue       Revenue     Revenue   Revenue
Category
Clothes          2.220630e+08  1.717425e+05   1245972.0    4985.0
Electronics      3.623063e+09  2.769926e+06  11182353.0  120655.0
Gadgets          2.654379e+09  2.594701e+06  23343582.0    9295.0
Groceries        2.394028e+07  2.365641e+04    350176.0     840.0
Home Appliances  5.584119e+08  1.094925e+06   6588592.0   81333.0

In [20]:
#Aggregate Units Sold by Sales Channel

channel_summary = pd.pivot_table(
    df,
    values="Units_Sold",
    index="Sales_Channel",
    aggfunc=["sum", "mean"]
)
channel_summary

                                    sum       mean
                             Units_Sold Units_Sold
Sales_Channel
Brandx_India App                45472.0  44.190476
Brandx_India Online             44598.0  43.982249
Brandx_India Phone Order        44919.0  44.342547
Brandx_India Social Commerce    44695.0  45.329615
Brandx_India Store              48799.0  44.201993

In [22]:
#Aggregate Revenue and Profit Margin by City

city_performance = pd.pivot_table(
    df,
    values=["Revenue", "Profit_Margin"],
    index="City",
    aggfunc={
        "Revenue": "sum",
        "Profit_Margin": "mean"
    }
)
city_performance

               Profit_Margin       Revenue
City
Ahmedabad          22.624845  2.655276e+08
Bangalore          22.830374  8.407997e+08
Bhopal             22.620614  1.079895e+08
Chennai            22.259758  7.419116e+08
Delhi              22.282928  1.661122e+09
Hyderabad          22.239853  6.597958e+08
Jaipur             22.326377  2.670945e+08
Kanpur             22.539515  8.430218e+07
Lucknow            22.070538  9.486221e+07
Mumbai             22.435763  1.674840e+09
Nagpur             22.342162  7.479879e+07
Pune               22.756934  2.936829e+08
Surat              22.883691  2.340634e+08
Visakhapatnam      22.574245  8.106636e+07

In [23]:
#Create Store Type Performance Report

store_summary = pd.pivot_table(
    df,
    values=["Revenue", "Units_Sold"],
    index="Store_Type",
    aggfunc="sum"
)

store_summary

                   Revenue  Units_Sold
Store_Type
Express       1.438936e+09     45493.0
Flagship      1.413566e+09     46443.0
Mall Store    1.492527e+09     47919.0
Online Hub    1.442170e+09     44442.0
Street Store  1.294659e+09     44186.0

In [ ]:
#countof category, count of subcategory, average(brand awarenes) brand performance

In [26]:
retail.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,Bx_Pune_034,Brandx_India Superstore Pune,Brandx_India,Flagship,Pune,Tier1,Green Tea 100G,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57.0,1,2022,Q1,Spring
1,Bx_Mumbai_023,Brandx_India Superstore Mumbai,Brandx_India,Street Store,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99.0,1,2022,Q1,Spring
2,Bx_Pune_073,Brandx_India Trends Pune,Brandx_India,Flagship,Pune,Tier1,Levi'S T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101.0,1,2022,Q1,Spring
3,Bx_Chennai_061,Brandx_India Trends Chennai,Brandx_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79.0,1,2022,Q1,Spring
4,Bx_Chennai_033,Brandx_India Connect Chennai,Brandx_India,Mall Store,Chennai,Metro,Playstation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110.0,1,2022,Q1,Spring

In [29]:
#Aggregate Revenue and Profit Margin by City

city_performance = pd.pivot_table(
    df,
    values=["Brand_Awareness", "Brand_Loyalty"],
    index="City",
    aggfunc={
        "Brand_Awareness": "mean",
        "Brand_Loyalty": "mean"
    }
)
city_performance

               Brand_Awareness  Brand_Loyalty
City
Ahmedabad            77.978682      75.319380
Bangalore            85.190354      84.052165
Bhopal               65.055263      75.357018
Chennai              85.097782      84.036694
Delhi                84.939438      83.772257
Hyderabad            85.129895      83.831158
Jaipur               65.009783      75.507246
Kanpur               65.353398      75.785437
Lucknow              65.206452      75.467742
Mumbai               85.131627      83.652108
Nagpur               64.681982      75.569369
Pune                 78.103650      75.877737
Surat                64.642060      76.142918
Visakhapatnam        65.089623      76.001887

In [30]:
#Aggregate Revenue and Profit Margin by City

city_performance = pd.pivot_table(
    df,
    values=["Category", "Sub_Category"],
    index="City",
    aggfunc={
        "Category": "count",
        "Sub_Category": "count"
    }
)
city_performance

               Category  Sub_Category
City
Ahmedabad           258           258
Bangalore           508           508
Bhopal              114           114
Chennai             496           496
Delhi              1103          1103
Hyderabad           475           475
Jaipur              276           276
Kanpur              103           103
Lucknow              93            93
Mumbai              996           996
Nagpur              111           111
Pune                274           274
Surat               233           233
Visakhapatnam       106           106